import { Octokit } from "@octokit/rest";
import { NextResponse } from "next/server";

export async function POST(req: Request) {
  try {
    const { gherkin, code, language, story, accessCode } = await req.json();

    // 1. Security check (same as generate route)
    const requiredCode = process.env.SPECS_ACCESS_CODE || "DemoSpecs2026";
    if (!accessCode || accessCode.trim() !== requiredCode.trim()) {
      return NextResponse.json(
        { error: "Unauthorized: Invalid access passcode." },
        { status: 401 }
      );
    }

    // 2. GitHub Configuration
    const token = process.env.GITHUB_TOKEN;
    const owner = process.env.GITHUB_OWNER || "pdabholegithub";
    const repo = process.env.GITHUB_REPO || "specs-ai";

    if (!token || token.includes("your_personal_access_token")) {
      return NextResponse.json(
        { error: "GitHub Integration not configured. Please add GITHUB_TOKEN to .env.local" },
        { status: 500 }
      );
    }

    const octokit = new Octokit({ auth: token });
    const timestamp = Date.now();
    const branchName = `syncflow/feature-${timestamp}`;
    const mainBranch = "main";

    // 3. Get main branch reference
    const { data: refData } = await octokit.git.getRef({
      owner,
      repo,
      ref: `heads/${mainBranch}`,
    });
    const latestCommitSha = refData.object.sha;

    // 4. Create new branch
    await octokit.git.createRef({
      owner,
      repo,
      ref: `refs/heads/${branchName}`,
      sha: latestCommitSha,
    });

    // 5. Prepare files to commit
    const fileExtension = language === "TypeScript" ? "spec.ts" : language === "Python" ? "py" : "java";
    const fileName = `tests/syncflow_gen_${timestamp}.${fileExtension}`;
    const gherkinFileName = `tests/syncflow_gen_${timestamp}.feature`;

    const files = [
      {
        path: fileName,
        content: code,
        message: `feat(test): add automated ${language} test for ${story.substring(0, 30)}...`,
      },
      {
        path: gherkinFileName,
        content: gherkin,
        message: `feat(spec): add Gherkin scenarios for ${story.substring(0, 30)}...`,
      },
    ];

    // 6. Commit files (Sequentially for simplicity in MVP)
    for (const file of files) {
      // Get file SHA if it exists (though it shouldn't for timestamped names)
      let currentFileSha: string | undefined;
      try {
        const { data: fileData } = await octokit.repos.getContent({
          owner,
          repo,
          path: file.path,
          ref: branchName,
        });
        if (!Array.isArray(fileData)) {
          currentFileSha = fileData.sha;
        }
      } catch (e) {
        // File doesn't exist, which is expected
      }

      await octokit.repos.createOrUpdateFileContents({
        owner,
        repo,
        path: file.path,
        message: file.message,
        content: Buffer.from(file.content).toString("base64"),
        branch: branchName,
        sha: currentFileSha,
      });
    }

    // 7. Create Pull Request
    const { data: prData } = await octokit.pulls.create({
      owner,
      repo,
      title: `🚀 [SyncFlow] Autonomous Test Suite: ${story.substring(0, 50)}...`,
      head: branchName,
      base: mainBranch,
      draft: true,
      body: `## 🤖 SyncFlow Autonomous PR
This PR was automatically generated by **SpecsAI (SyncFlow)** based on the following requirement:

> ${story}

### 📦 Included Assets:
1. **Gherkin Spec**: \`${gherkinFileName}\`
2. **Automation Script**: \`${fileName}\` (${language})

---
*Generated with ❤️ by SpecsAI v2.5*`,
    });

    return NextResponse.json({
      success: true,
      prUrl: prData.html_url,
      branch: branchName,
    });

  } catch (error: any) {
    console.error("[GITHUB EXPORT ERROR]", error);
    return NextResponse.json(
      { error: error.message || "Failed to create GitHub PR" },
      { status: 500 }
    );
  }
}
