const fs = require('fs');
const path = require('path');

function findFailingFile(logs) {
  // Regex to find Playwright failure patterns: [project] › filename.spec.ts:line:col
  // Or general paths like tests/auth.spec.ts
  const playwrightRegex = /([a-zA-Z0-9_\-\/]+\.spec\.(ts|js))/;
  const match = logs.match(playwrightRegex);
  return match ? match[1] : null;
}

function findScreenshot() {
  const resultsDir = path.resolve('test-results');
  if (!fs.existsSync(resultsDir)) return null;

  // Recursively find the first .png file in test-results
  const findImage = (dir) => {
    const files = fs.readdirSync(dir);
    for (const file of files) {
      const fullPath = path.join(dir, file);
      if (fs.statSync(fullPath).isDirectory()) {
        const found = findImage(fullPath);
        if (found) return found;
      } else if (file.endsWith('.png')) {
        return fullPath;
      }
    }
    return null;
  };

  return findImage(resultsDir);
}

async function heal() {
  const errorLogs = process.env.FAILURE_LOGS;
  let filePath = process.env.FAILING_FILE;
  const apiEndpoint = process.env.SYNCFLOW_API_URL || 'https://your-app.vercel.app/api/ai/heal';
  const accessCode = process.env.SPECS_ACCESS_CODE || 'DemoSpecs2026';

  if (!errorLogs) {
    console.error("Missing FAILURE_LOGS env variable.");
    process.exit(1);
  }

  // Auto-detect failing file if not provided
  if (!filePath || filePath === 'tests/example.spec.ts') {
    console.log("🔍 SyncFlow: Detecting failing file from logs...");
    filePath = findFailingFile(errorLogs);
  }

  if (!filePath) {
    console.error("❌ SyncFlow: Could not detect which file failed. Please check logs.");
    process.exit(1);
  }

  const resolvedPath = path.resolve(filePath);
  if (!fs.existsSync(resolvedPath)) {
    console.error(`File not found: ${resolvedPath}`);
    process.exit(1);
  }

  const originalCode = fs.readFileSync(resolvedPath, 'utf8');

  // Look for a screenshot to provide visual context
  let screenshot = null;
  const screenshotPath = findScreenshot();
  if (screenshotPath) {
    console.log(`📸 SyncFlow: Found failure screenshot at ${screenshotPath}. Adding visual context...`);
    screenshot = fs.readFileSync(screenshotPath, 'base64');
  }

  console.log(`🤖 SyncFlow: Sending failure data to AI Healing Core...`);

  try {
    const response = await fetch(apiEndpoint, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        errorLogs,
        originalCode,
        filePath,
        accessCode,
        screenshot
      })
    });

    const data = await response.json();

    if (data.healedCode) {
      console.log(`✅ SyncFlow: AI Diagnosis complete.`);
      console.log(`Root Cause Analysis: ${data.analysis}`);
      
      // Update the file with healed code
      fs.writeFileSync(resolvedPath, data.healedCode, 'utf8');
      
      // Generate Diagnosis Markdown for PR Body
      const diagnosisMd = `### 🛡️ SyncFlow Autonomous Diagnosis
**Status:** ✅ Fix Generated
**Target File:** \`${filePath}\`
**Visual Healing:** ${screenshot ? '📸 Enabled (Screenshot Analyzed)' : '📝 Logs Only'}

#### 🔍 Root Cause Analysis
${data.analysis || 'The AI identified a logic or syntax error in the test execution and applied a corrective patch.'}

#### 🛠️ Applied Changes
- Analyzed failure logs and original source code.
${screenshot ? '- Correlated error with visual state from screenshot.' : ''}
- Applied the most likely corrective fix.
- *This is an autonomous fix. Please review carefully before merging.*

---
*Generated by [SyncFlow AI](https://syncflow.ai)*`;
      
      fs.writeFileSync('diagnosis.md', diagnosisMd, 'utf8');
      
      // Save to Historical Memory
      const historyDir = path.resolve('src/data/healing-history');
      if (!fs.existsSync(historyDir)) fs.mkdirSync(historyDir, { recursive: true });
      
      const knowledgeItem = {
        timestamp: new Date().toISOString(),
        filePath,
        analysis: data.analysis,
        errorLogs: errorLogs.substring(0, 500), // Only save the relevant part
        visualContext: !!screenshot
      };
      
      const historyFile = path.join(historyDir, `fix-${Date.now()}.json`);
      fs.writeFileSync(historyFile, JSON.stringify(knowledgeItem, null, 2));
      
      console.log(`🎉 SyncFlow: File healed, diagnosis generated, and knowledge saved to memory!`);
    } else {
      console.error(`❌ SyncFlow: AI could not generate a fix. ${data.error || ''}`);
      process.exit(1);
    }
  } catch (err) {
    console.error(`❌ SyncFlow: Failed to connect to Healing API. ${err.message}`);
    process.exit(1);
  }
}

heal();
